version: "3.5"

services:
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
    - "9090:9090"

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=asdf123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ${PWD}/prometheus-ds.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ${PWD}/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"
